name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '新增功能'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '改进'
    labels:
      - 'improvement'
      - 'optimization'
      - 'refactor'
  - title: '修复的Bug'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '已知问题'
    labels:
      - 'known issue'
      - 'known-issue'
  - title: '升级指南'
    labels:
      - 'breaking'
      - 'breaking-change'

change-template: '- $TITLE (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'breaking'
      - 'breaking-change'
  minor:
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  default: patch

template: |
  ## $RESOLVED_VERSION
  **发布日期:** $RELEASE_DATE

  $CHANGES

  ### 升级指南
  - 请在升级前查看上述变更内容，确保您的应用程序兼容这些更改
  - 如果存在数据库结构变更，请务必先备份数据再进行升级
